spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.paths-to-match=/api/**
springdoc.use-fqn=true

