spring.application.name=caddycom

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:caddycom
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.paths-to-match=/api/**
springdoc.use-fqn=true

